### ISSUE TITLE
'expressions' : a namespace with this name does not exist

### ISSUE THREAD

**Issue by zecoxao** [nihilus/snowman#25]
Here are the logs:
Cmake:
http://pastie.org/10340195
Cmake warnings:
http://pastie.org/10340198
And finally, the errors:
http://pastie.org/10340207
Maybe they happen because i'm using Visual Studio 2010?

**Comment by hlide** [comment]
- Cmake: sounds ok (there are stuff not mandatory)
- Cmake warnings: they are the orginal ones, we never change them. As for Qt5, it should be a problem since you appear to go for Qt 4.
- Errors: I cannot say more since it is not my last version of Allegrex source.

**Comment by nihilus** [comment]
Might be this 'using namespace core::irgen::expressions;'

**Comment by hlide** [comment]
try with VS2013

**Comment by zecoxao** [comment]
ok. i'll try. thanks

**Comment by techbliss** [comment]
its building fine on vs 2013 
I get the same warnings in Cmake.
my cmake configure command is 
`cmake -G "Visual Studio 12" -D -DCMAKE_BUILD_TYPE=Release -D QT_NAMESPACE=QT -D IDA_PLUGIN_ENABLED=YES -D IDA_64_BIT_EA_T=NO -D NC_QT5=NO ../src`

I however build in vs 2013, since  cmake build fails in prompt.
Also you would have to add idasdk include folders and ida.lib, if you want the ida plugin.Its not found by Cmake i see.

if you just wanna test snowman, here is the build i just made.
https://mega.co.nz/#!XpN23STB!PldhmYMH870srqetRJpCqHtxNLnLycMZ66YI2bu_eRA

**Comment by hlide** [comment]
If Allegrex is to be tested, it is better to take it from my repository. If MIPS is to be tested, Nihilus' repository is the right one.

**Comment by hlide** [comment]
It would be good to install an appveyor script fro windows and another one for linux

**Comment by techbliss** [comment]
Also xecosao keep in mind, that it will properly build debug to start with, even with release syntax 
https://github.com/yegord/snowman/issues/31
And yes agree scripts always helps

**Comment by zecoxao** [comment]
just compiled in visual studio 2013. doesn't fail. thanks for the testing
